"""
citategenie/engines/publisher_places.py

Comprehensive publisher-to-place mapping for citation formatting.
Contains 500+ publishers with authoritative publication places.

Version: 2025-12-20 V1.0
"""

from typing import Optional, Dict

# =============================================================================
# CONSOLIDATED PUBLISHER DATABASE
# =============================================================================

PUBLISHER_PLACES: Dict[str, str] = {
    # =========================================================================
    # US UNIVERSITY PRESSES
    # =========================================================================
    "Harvard University Press": "Cambridge, MA",
    "Yale University Press": "New Haven, CT",
    "Princeton University Press": "Princeton, NJ",
    "Columbia University Press": "New York",
    "University of Pennsylvania Press": "Philadelphia",
    "Cornell University Press": "Ithaca, NY",
    "University of Chicago Press": "Chicago",
    "MIT Press": "Cambridge, MA",
    "Stanford University Press": "Stanford, CA",
    "University of California Press": "Berkeley",
    "UC Press": "Berkeley",
    "Johns Hopkins University Press": "Baltimore",
    "Duke University Press": "Durham, NC",
    "University of North Carolina Press": "Chapel Hill",
    "University of Virginia Press": "Charlottesville",
    "University of Texas Press": "Austin",
    "University of Michigan Press": "Ann Arbor",
    "University of Wisconsin Press": "Madison",
    "University of Minnesota Press": "Minneapolis",
    "University of Illinois Press": "Urbana",
    "Northwestern University Press": "Evanston, IL",
    "Indiana University Press": "Bloomington",
    "Ohio State University Press": "Columbus",
    "Penn State University Press": "University Park, PA",
    "University of Pittsburgh Press": "Pittsburgh",
    "Rutgers University Press": "New Brunswick, NJ",
    "New York University Press": "New York",
    "NYU Press": "New York",
    "SUNY Press": "Albany, NY",
    "State University of New York Press": "Albany, NY",
    "University of Georgia Press": "Athens, GA",
    "University of South Carolina Press": "Columbia, SC",
    "Louisiana State University Press": "Baton Rouge",
    "LSU Press": "Baton Rouge",
    "University of Alabama Press": "Tuscaloosa",
    "University of Tennessee Press": "Knoxville",
    "University Press of Florida": "Gainesville",
    "University Press of Mississippi": "Jackson",
    "University of Arkansas Press": "Fayetteville",
    "University of Oklahoma Press": "Norman",
    "University of Nebraska Press": "Lincoln",
    "University Press of Kansas": "Lawrence",
    "University of Iowa Press": "Iowa City",
    "University of Missouri Press": "Columbia, MO",
    "University of Washington Press": "Seattle",
    "Oregon State University Press": "Corvallis",
    "University of Arizona Press": "Tucson",
    "University of New Mexico Press": "Albuquerque",
    "University Press of Colorado": "Boulder",
    "Utah State University Press": "Logan",
    "University of Utah Press": "Salt Lake City",
    "University of Nevada Press": "Reno",
    "University of Hawai'i Press": "Honolulu",
    "University of Hawaii Press": "Honolulu",
    "Georgetown University Press": "Washington, DC",
    "Catholic University of America Press": "Washington, DC",
    "Fordham University Press": "New York",
    "Temple University Press": "Philadelphia",
    "University of Massachusetts Press": "Amherst",
    "Wesleyan University Press": "Middletown, CT",
    "University of Notre Dame Press": "Notre Dame, IN",
    "Vanderbilt University Press": "Nashville",
    "University of Kentucky Press": "Lexington",
    "West Virginia University Press": "Morgantown",
    "Wayne State University Press": "Detroit",
    "Southern Illinois University Press": "Carbondale",
    "Purdue University Press": "West Lafayette, IN",
    "Kent State University Press": "Kent, OH",
    "Texas A&M University Press": "College Station",
    "Baylor University Press": "Waco, TX",
    
    # =========================================================================
    # UK UNIVERSITY PRESSES
    # =========================================================================
    "Oxford University Press": "Oxford",
    "OUP": "Oxford",
    "Cambridge University Press": "Cambridge",
    "CUP": "Cambridge",
    "Edinburgh University Press": "Edinburgh",
    "Manchester University Press": "Manchester",
    "Liverpool University Press": "Liverpool",
    "University of Wales Press": "Cardiff",
    "Bristol University Press": "Bristol",
    "UCL Press": "London",
    "Polity Press": "Cambridge",
    "Polity": "Cambridge",
    
    # =========================================================================
    # CANADA UNIVERSITY PRESSES
    # =========================================================================
    "University of Toronto Press": "Toronto",
    "McGill-Queen's University Press": "Montreal",
    "University of British Columbia Press": "Vancouver",
    "UBC Press": "Vancouver",
    "University of Alberta Press": "Edmonton",
    "University of Calgary Press": "Calgary",
    "University of Manitoba Press": "Winnipeg",
    "Wilfrid Laurier University Press": "Waterloo, ON",
    "University of Ottawa Press": "Ottawa",
    
    # =========================================================================
    # AUSTRALIA/NZ UNIVERSITY PRESSES
    # =========================================================================
    "Melbourne University Press": "Melbourne",
    "Sydney University Press": "Sydney",
    "University of Queensland Press": "Brisbane",
    "University of Western Australia Press": "Perth",
    "UNSW Press": "Sydney",
    "NewSouth Publishing": "Sydney",
    "ANU Press": "Canberra",
    "Auckland University Press": "Auckland",
    "Victoria University Press": "Wellington",
    "Otago University Press": "Dunedin",
    
    # =========================================================================
    # EUROPE UNIVERSITY PRESSES
    # =========================================================================
    "Presses Universitaires de France": "Paris",
    "PUF": "Paris",
    "Amsterdam University Press": "Amsterdam",
    "Leiden University Press": "Leiden",
    "Leuven University Press": "Leuven",
    "Firenze University Press": "Florence",
    "Il Mulino": "Bologna",
    "Aarhus University Press": "Aarhus",
    "Stockholm University Press": "Stockholm",
    "Universitetsforlaget": "Oslo",
    
    # =========================================================================
    # PENGUIN RANDOM HOUSE IMPRINTS
    # =========================================================================
    "Penguin Random House": "New York",
    "Penguin": "New York",
    "Penguin Books": "New York",
    "Penguin Press": "New York",
    "Penguin Classics": "New York",
    "Viking": "New York",
    "Viking Press": "New York",
    "Putnam": "New York",
    "G.P. Putnam's Sons": "New York",
    "Riverhead Books": "New York",
    "Riverhead": "New York",
    "Dutton": "New York",
    "Berkley": "New York",
    "Ace Books": "New York",
    "Ace": "New York",
    "Plume": "New York",
    "Dial Press": "New York",
    "The Dial Press": "New York",
    "Avery": "New York",
    "Portfolio": "New York",
    "Random House": "New York",
    "Ballantine Books": "New York",
    "Ballantine": "New York",
    "Bantam": "New York",
    "Bantam Books": "New York",
    "Dell": "New York",
    "Delacorte Press": "New York",
    "Delacorte": "New York",
    "Del Rey": "New York",
    "Del Rey Books": "New York",
    "Modern Library": "New York",
    "The Modern Library": "New York",
    "One World": "New York",
    "Spiegel & Grau": "New York",
    "Hogarth": "New York",
    "Convergent": "New York",
    "WaterBrook": "Colorado Springs, CO",
    "Multnomah": "Colorado Springs, CO",
    "Knopf": "New York",
    "Alfred A. Knopf": "New York",
    "Doubleday": "New York",
    "Anchor Books": "New York",
    "Anchor": "New York",
    "Everyman's Library": "New York",
    "Pantheon": "New York",
    "Pantheon Books": "New York",
    "Schocken": "New York",
    "Schocken Books": "New York",
    "Vintage": "New York",
    "Vintage Books": "New York",
    "Nan A. Talese": "New York",
    "Crown": "New York",
    "Crown Publishing": "New York",
    "Three Rivers Press": "New York",
    "Harmony": "New York",
    "Harmony Books": "New York",
    "Rodale": "New York",
    "Rodale Books": "New York",
    "Ten Speed Press": "Berkeley",
    "Clarkson Potter": "New York",
    "Currency": "New York",
    # PRH UK
    "Penguin UK": "London",
    "Hamish Hamilton": "London",
    "Allen Lane": "London",
    "Pelican": "London",
    "Pelican Books": "London",
    "Puffin": "London",
    "Michael Joseph": "London",
    "Century": "London",
    "Hutchinson": "London",
    "William Heinemann": "London",
    "Heinemann": "London",
    "Ebury": "London",
    "Ebury Press": "London",
    "Transworld": "London",
    "Bantam Press": "London",
    "Corgi": "London",
    "Black Swan": "London",
    "Chatto & Windus": "London",
    "Jonathan Cape": "London",
    "Bodley Head": "London",
    "The Bodley Head": "London",
    "Harvill Secker": "London",
    "Yellow Jersey Press": "London",
    
    # =========================================================================
    # HARPERCOLLINS IMPRINTS
    # =========================================================================
    "HarperCollins": "New York",
    "Harper": "New York",
    "HarperOne": "New York",
    "Harper Perennial": "New York",
    "Ecco": "New York",
    "Ecco Press": "New York",
    "William Morrow": "New York",
    "Morrow": "New York",
    "Avon": "New York",
    "Avon Books": "New York",
    "Dey Street": "New York",
    "Harper Voyager": "New York",
    "Harper Wave": "New York",
    "Amistad": "New York",
    "Harper Business": "New York",
    "HarperBusiness": "New York",
    "Thomas Nelson": "Nashville",
    "Zondervan": "Grand Rapids, MI",
    "Zondervan Academic": "Grand Rapids, MI",
    "Nelson Books": "Nashville",
    "Harlequin": "Toronto",
    "Harlequin Books": "Toronto",
    "MIRA": "Toronto",
    "Park Row Books": "Toronto",
    "Hanover Square Press": "Toronto",
    # HC UK
    "HarperCollins UK": "London",
    "The Borough Press": "London",
    "Fourth Estate": "London",
    "William Collins": "London",
    "Collins": "London",
    "Thorsons": "London",
    "HarperCollins Australia": "Sydney",
    "HarperCollins India": "New Delhi",
    
    # =========================================================================
    # SIMON & SCHUSTER IMPRINTS
    # =========================================================================
    "Simon & Schuster": "New York",
    "Simon and Schuster": "New York",
    "Scribner": "New York",
    "Scribner's": "New York",
    "Charles Scribner's Sons": "New York",
    "Atria": "New York",
    "Atria Books": "New York",
    "Free Press": "New York",
    "Gallery Books": "New York",
    "Gallery": "New York",
    "Pocket Books": "New York",
    "Pocket": "New York",
    "Threshold Editions": "New York",
    "Touchstone": "New York",
    "Simon & Schuster UK": "London",
    
    # =========================================================================
    # MACMILLAN IMPRINTS
    # =========================================================================
    "Macmillan": "New York",
    "Macmillan Publishers": "New York",
    "Farrar, Straus and Giroux": "New York",
    "FSG": "New York",
    "Hill and Wang": "New York",
    "Hill & Wang": "New York",
    "North Point Press": "New York",
    "MCD": "New York",
    "Flatiron Books": "New York",
    "Flatiron": "New York",
    "Henry Holt": "New York",
    "Henry Holt and Company": "New York",
    "Holt": "New York",
    "Metropolitan Books": "New York",
    "Metropolitan": "New York",
    "Times Books": "New York",
    "Picador": "New York",
    "Picador USA": "New York",
    "St. Martin's Press": "New York",
    "St. Martin's": "New York",
    "St Martin's Press": "New York",
    "Minotaur Books": "New York",
    "Minotaur": "New York",
    "St. Martin's Griffin": "New York",
    "Thomas Dunne Books": "New York",
    "Wednesday Books": "New York",
    "Celadon Books": "New York",
    "Celadon": "New York",
    "Tor": "New York",
    "Tor Books": "New York",
    "Forge": "New York",
    "Forge Books": "New York",
    "Tor.com Publishing": "New York",
    # Macmillan UK
    "Pan Macmillan": "London",
    "Pan Books": "London",
    "Picador UK": "London",
    "Mantle": "London",
    "Palgrave Macmillan": "London",
    "Palgrave": "London",
    
    # =========================================================================
    # HACHETTE IMPRINTS
    # =========================================================================
    "Hachette Book Group": "New York",
    "Hachette": "New York",
    "Grand Central Publishing": "New York",
    "Grand Central": "New York",
    "Forever": "New York",
    "Twelve": "New York",
    "Little, Brown": "New York",
    "Little, Brown and Company": "New York",
    "Little Brown": "New York",
    "Back Bay Books": "New York",
    "Mulholland Books": "New York",
    "Voracious": "New York",
    "Little, Brown Spark": "New York",
    "Hachette Books": "New York",
    "PublicAffairs": "New York",
    "Public Affairs": "New York",
    "Basic Books": "New York",
    "Seal Press": "New York",
    "Da Capo Press": "New York",
    "Da Capo": "New York",
    "Running Press": "Philadelphia",
    "Perseus Books": "New York",
    "Bold Type Books": "New York",
    "Orbit": "New York",
    "Orbit Books": "New York",
    "Workman": "New York",
    "Workman Publishing": "New York",
    "Algonquin Books": "Chapel Hill, NC",
    "Algonquin": "Chapel Hill, NC",
    "Artisan": "New York",
    "Storey Publishing": "North Adams, MA",
    "Timber Press": "Portland, OR",
    # Hachette UK
    "Hachette UK": "London",
    "Hodder & Stoughton": "London",
    "Hodder": "London",
    "Sceptre": "London",
    "John Murray": "London",
    "John Murray Press": "London",
    "Two Roads": "London",
    "Headline": "London",
    "Headline Publishing": "London",
    "Little, Brown UK": "London",
    "Little, Brown Book Group": "London",
    "Sphere": "London",
    "Constable": "London",
    "Piatkus": "London",
    "Virago": "London",
    "Virago Press": "London",
    "Abacus": "London",
    "Fleet": "London",
    "Gollancz": "London",
    "Victor Gollancz": "London",
    "Orion": "London",
    "Orion Books": "London",
    "Weidenfeld & Nicolson": "London",
    "Weidenfeld and Nicolson": "London",
    "Quercus": "London",
    "MacLehose Press": "London",
    "Hachette Australia": "Sydney",
    "Hachette India": "New Delhi",
    
    # =========================================================================
    # MAJOR INDEPENDENTS - US
    # =========================================================================
    "W. W. Norton": "New York",
    "W.W. Norton": "New York",
    "Norton": "New York",
    "Liveright": "New York",
    "Liveright Publishing": "New York",
    "Grove Atlantic": "New York",
    "Grove Press": "New York",
    "Grove": "New York",
    "Atlantic Monthly Press": "New York",
    "Counterpoint": "Berkeley",
    "Counterpoint Press": "Berkeley",
    "Soft Skull Press": "Berkeley",
    "Catapult": "New York",
    "Graywolf Press": "Minneapolis",
    "Graywolf": "Minneapolis",
    "Coffee House Press": "Minneapolis",
    "Milkweed Editions": "Minneapolis",
    "Milkweed": "Minneapolis",
    "Melville House": "Brooklyn, NY",
    "New Directions": "New York",
    "New Directions Publishing": "New York",
    "Archipelago Books": "Brooklyn, NY",
    "Europa Editions": "New York",
    "Other Press": "New York",
    "The Other Press": "New York",
    "Seven Stories Press": "New York",
    "Verso": "London",
    "Verso Books": "London",
    "Haymarket Books": "Chicago",
    "The New Press": "New York",
    "New Press": "New York",
    "Beacon Press": "Boston",
    "Beacon": "Boston",
    "Soho Press": "New York",
    "Soho Crime": "New York",
    "Akashic Books": "Brooklyn, NY",
    "City Lights": "San Francisco",
    "City Lights Books": "San Francisco",
    "Tin House": "Portland, OR",
    "Tin House Books": "Portland, OR",
    "McSweeney's": "San Francisco",
    "Copper Canyon Press": "Port Townsend, WA",
    "Sarabande Books": "Louisville, KY",
    "Dzanc Books": "Ann Arbor, MI",
    "Two Dollar Radio": "Columbus, OH",
    "Restless Books": "Brooklyn, NY",
    "Deep Vellum": "Dallas",
    "Pushkin Press": "London",
    "Berrett-Koehler": "Oakland, CA",
    "BenBella Books": "Dallas",
    "Sounds True": "Boulder, CO",
    "Kensington": "New York",
    "Kensington Publishing": "New York",
    "Sourcebooks": "Naperville, IL",
    "Poisoned Pen Press": "Naperville, IL",
    "Tyndale": "Carol Stream, IL",
    "Tyndale House": "Carol Stream, IL",
    "Revell": "Grand Rapids, MI",
    "Bethany House": "Minneapolis",
    "Baker Books": "Grand Rapids, MI",
    "Baker Publishing Group": "Grand Rapids, MI",
    "Brazos Press": "Grand Rapids, MI",
    "Harvest House": "Eugene, OR",
    "Moody Publishers": "Chicago",
    "Crossway": "Wheaton, IL",
    "InterVarsity Press": "Downers Grove, IL",
    "IVP": "Downers Grove, IL",
    "IVP Academic": "Downers Grove, IL",
    "Eerdmans": "Grand Rapids, MI",
    "Wm. B. Eerdmans": "Grand Rapids, MI",
    "William B. Eerdmans": "Grand Rapids, MI",
    "Scholastic": "New York",
    "Scholastic Press": "New York",
    "Chronicle Books": "San Francisco",
    "Chronicle": "San Francisco",
    "Abrams": "New York",
    "Harry N. Abrams": "New York",
    "Abrams Books": "New York",
    "Abrams Press": "New York",
    "Amulet Books": "New York",
    "Candlewick Press": "Somerville, MA",
    "Candlewick": "Somerville, MA",
    "Holiday House": "New York",
    "Peachtree": "Atlanta",
    "Charlesbridge": "Watertown, MA",
    "Boyds Mills Press": "Honesdale, PA",
    "Phaidon": "London",
    "Phaidon Press": "London",
    "Taschen": "Cologne",
    "TASCHEN": "Cologne",
    "Thames & Hudson": "London",
    "Thames and Hudson": "London",
    "Rizzoli": "New York",
    "Rizzoli International": "New York",
    "Prestel": "Munich",
    "Aperture": "New York",
    "Princeton Architectural Press": "New York",
    "Laurence King": "London",
    "Gestalten": "Berlin",
    
    # =========================================================================
    # MAJOR INDEPENDENTS - UK
    # =========================================================================
    "Faber & Faber": "London",
    "Faber and Faber": "London",
    "Faber": "London",
    "Bloomsbury": "London",
    "Bloomsbury Publishing": "London",
    "Bloomsbury Academic": "London",
    "Granta": "London",
    "Granta Books": "London",
    "Profile Books": "London",
    "Profile": "London",
    "Serpent's Tail": "London",
    "Canongate": "Edinburgh",
    "Canongate Books": "Edinburgh",
    "Atlantic Books": "London",
    "Allen & Unwin": "Sydney",
    "Allen and Unwin": "Sydney",
    "Head of Zeus": "London",
    "Bonnier Books UK": "London",
    "Unbound": "London",
    "Oneworld Publications": "London",
    "Oneworld": "London",
    "Icon Books": "London",
    "Biteback Publishing": "London",
    "Duckworth": "London",
    "Overlook Press": "New York",
    "The Overlook Press": "New York",
    "Carcanet": "Manchester",
    "Carcanet Press": "Manchester",
    "Bloodaxe Books": "Eastburn",
    "Fitzcarraldo Editions": "London",
    "And Other Stories": "Sheffield",
    "Birlinn": "Edinburgh",
    "Polygon": "Edinburgh",
    
    # =========================================================================
    # MAJOR INDEPENDENTS - EUROPE
    # =========================================================================
    # Germany
    "Suhrkamp": "Berlin",
    "Suhrkamp Verlag": "Berlin",
    "S. Fischer": "Frankfurt",
    "S. Fischer Verlag": "Frankfurt",
    "Rowohlt": "Hamburg",
    "Hanser": "Munich",
    "Carl Hanser Verlag": "Munich",
    "C.H. Beck": "Munich",
    "C. H. Beck": "Munich",
    "Beck": "Munich",
    "Klett-Cotta": "Stuttgart",
    "Diogenes": "Zurich",
    "Diogenes Verlag": "Zurich",
    "Aufbau": "Berlin",
    "Aufbau Verlag": "Berlin",
    "Piper": "Munich",
    "DTV": "Munich",
    "Ullstein": "Berlin",
    "Kiepenheuer & Witsch": "Cologne",
    "Wallstein": "Göttingen",
    # France
    "Gallimard": "Paris",
    "Éditions Gallimard": "Paris",
    "Folio": "Paris",
    "Seuil": "Paris",
    "Éditions du Seuil": "Paris",
    "Flammarion": "Paris",
    "Grasset": "Paris",
    "Albin Michel": "Paris",
    "Stock": "Paris",
    "Minuit": "Paris",
    "Les Éditions de Minuit": "Paris",
    "Actes Sud": "Arles",
    "POL": "Paris",
    "Fayard": "Paris",
    "Calmann-Lévy": "Paris",
    "Robert Laffont": "Paris",
    "JC Lattès": "Paris",
    "La Découverte": "Paris",
    "Verdier": "Lagrasse",
    # Spain
    "Anagrama": "Barcelona",
    "Tusquets": "Barcelona",
    "Seix Barral": "Barcelona",
    "Planeta": "Barcelona",
    "Alfaguara": "Madrid",
    "Salamandra": "Barcelona",
    "Destino": "Barcelona",
    "Acantilado": "Barcelona",
    "Siruela": "Madrid",
    # Italy
    "Einaudi": "Turin",
    "Mondadori": "Milan",
    "Feltrinelli": "Milan",
    "Adelphi": "Milan",
    "Bompiani": "Milan",
    "Laterza": "Bari",
    "Sellerio": "Palermo",
    "E/O": "Rome",
    "Neri Pozza": "Vicenza",
    "Marsilio": "Venice",
    "Bollati Boringhieri": "Turin",
    # Netherlands
    "De Bezige Bij": "Amsterdam",
    "Meulenhoff": "Amsterdam",
    "Atlas Contact": "Amsterdam",
    "Prometheus": "Amsterdam",
    "Querido": "Amsterdam",
    "Arbeiderspers": "Amsterdam",
    # Scandinavia
    "Gyldendal": "Copenhagen",
    "Aschehoug": "Oslo",
    "Cappelen Damm": "Oslo",
    "Bonnier": "Stockholm",
    "Norstedts": "Stockholm",
    
    # =========================================================================
    # ACADEMIC/SCHOLARLY PUBLISHERS
    # =========================================================================
    "Springer": "Berlin",
    "Springer-Verlag": "Berlin",
    "Springer Nature": "Berlin",
    "Elsevier": "Amsterdam",
    "Elsevier Science": "Amsterdam",
    "Academic Press": "San Diego",
    "North-Holland": "Amsterdam",
    "Pergamon": "Oxford",
    "Pergamon Press": "Oxford",
    "Wiley": "Hoboken, NJ",
    "John Wiley & Sons": "Hoboken, NJ",
    "Wiley-Blackwell": "Hoboken, NJ",
    "Blackwell": "Oxford",
    "Blackwell Publishing": "Oxford",
    "Wiley-VCH": "Weinheim",
    "SAGE": "Thousand Oaks, CA",
    "SAGE Publications": "Thousand Oaks, CA",
    "Sage Publications": "Thousand Oaks, CA",
    "Sage": "Thousand Oaks, CA",
    "De Gruyter": "Berlin",
    "Walter de Gruyter": "Berlin",
    "Mouton de Gruyter": "Berlin",
    "Brill": "Leiden",
    "E.J. Brill": "Leiden",
    "Brill Nijhoff": "Leiden",
    "Rodopi": "Amsterdam",
    "Benjamins": "Amsterdam",
    "John Benjamins": "Amsterdam",
    "Karger": "Basel",
    "S. Karger": "Basel",
    "Thieme": "Stuttgart",
    "Georg Thieme Verlag": "Stuttgart",
    "Lippincott Williams & Wilkins": "Philadelphia",
    "Lippincott": "Philadelphia",
    "Wolters Kluwer": "Alphen aan den Rijn",
    "Kluwer": "Dordrecht",
    "Kluwer Academic": "Dordrecht",
    "Kluwer Law International": "Alphen aan den Rijn",
    "Taylor & Francis": "Abingdon",
    "Taylor and Francis": "Abingdon",
    "Routledge": "Abingdon",
    "Psychology Press": "Hove",
    "Ashgate": "Farnham",
    "Emerald": "Bingley",
    "Emerald Publishing": "Bingley",
    "IGI Global": "Hershey, PA",
    "IOS Press": "Amsterdam",
    "World Scientific": "Singapore",
    "Peter Lang": "Bern",
    "IEEE": "Piscataway, NJ",
    "IEEE Press": "Piscataway, NJ",
    "ACM": "New York",
    "ACM Press": "New York",
    "SIAM": "Philadelphia",
    "AMS": "Providence, RI",
    "American Mathematical Society": "Providence, RI",
    "ACS": "Washington, DC",
    "American Chemical Society": "Washington, DC",
    "RSC": "Cambridge",
    "Royal Society of Chemistry": "Cambridge",
    "IOP": "Bristol",
    "IOP Publishing": "Bristol",
    "MDPI": "Basel",
    "Frontiers": "Lausanne",
    "PLOS": "San Francisco",
    "eLife": "Cambridge",
    "BMJ": "London",
    "Nature Publishing Group": "London",
    "Nature": "London",
    
    # =========================================================================
    # LATIN AMERICA
    # =========================================================================
    "Fondo de Cultura Económica": "Mexico City",
    "FCE": "Mexico City",
    "El Colegio de México": "Mexico City",
    "Siglo XXI": "Mexico City",
    "Siglo XXI Editores": "Mexico City",
    "UNAM": "Mexico City",
    "Editora da Universidade de São Paulo": "São Paulo",
    "EDUSP": "São Paulo",
    "Companhia das Letras": "São Paulo",
    "Record": "Rio de Janeiro",
    "Objetiva": "Rio de Janeiro",
    "Rocco": "Rio de Janeiro",
    "EUDEBA": "Buenos Aires",
    "Emecé": "Buenos Aires",
    "Sudamericana": "Buenos Aires",
    
    # =========================================================================
    # ASIA
    # =========================================================================
    "Hong Kong University Press": "Hong Kong",
    "Chinese University Press": "Hong Kong",
    "NUS Press": "Singapore",
    "University of Tokyo Press": "Tokyo",
    "Kodansha": "Tokyo",
    "Shueisha": "Tokyo",
    "Orient Blackswan": "Hyderabad",
    "Penguin India": "New Delhi",
    "HarperCollins India": "New Delhi",
    "Peking University Press": "Beijing",
    "Tsinghua University Press": "Beijing",
    
    # =========================================================================
    # MIDDLE EAST / AFRICA
    # =========================================================================
    "Hebrew University Magnes Press": "Jerusalem",
    "Magnes Press": "Jerusalem",
    "Wits University Press": "Johannesburg",
    "University of Cape Town Press": "Cape Town",
    "HSRC Press": "Pretoria",
    "Jacana Media": "Auckland Park",
}


def get_publisher_place(publisher: str) -> Optional[str]:
    """
    Look up the publication place for a publisher.
    
    Args:
        publisher: Publisher name (exact or partial match)
        
    Returns:
        Publication place string, or None if not found
    """
    if not publisher:
        return None
    
    # Clean up publisher name
    publisher_clean = publisher.strip()
    
    # Try exact match first
    if publisher_clean in PUBLISHER_PLACES:
        return PUBLISHER_PLACES[publisher_clean]
    
    # Try case-insensitive match
    publisher_lower = publisher_clean.lower()
    for pub, place in PUBLISHER_PLACES.items():
        if pub.lower() == publisher_lower:
            return place
    
    # Try partial match (publisher contains key or key contains publisher)
    for pub, place in PUBLISHER_PLACES.items():
        pub_lower = pub.lower()
        if pub_lower in publisher_lower or publisher_lower in pub_lower:
            return place
    
    return None


def normalize_publisher_name(publisher: str) -> str:
    """
    Normalize publisher name for consistent matching.
    
    Args:
        publisher: Raw publisher name
        
    Returns:
        Normalized publisher name
    """
    if not publisher:
        return ""
    
    # Common normalizations
    normalized = publisher.strip()
    
    # Remove common suffixes
    suffixes = [
        ", Inc.", ", Inc", " Inc.", " Inc",
        ", LLC", " LLC",
        ", Ltd.", ", Ltd", " Ltd.", " Ltd",
        ", Limited", " Limited",
        " Publishing", " Publishers", " Publisher",
        " Press", " Books", " Editions",
    ]
    
    for suffix in suffixes:
        if normalized.endswith(suffix):
            normalized = normalized[:-len(suffix)]
    
    return normalized.strip()


# Export count for verification
PUBLISHER_COUNT = len(PUBLISHER_PLACES)
